atomic commit

diff --git a/scripts/i3-window-killer/install b/scripts/i3-window-killer/install
--- a/scripts/i3-window-killer/install
+++ b/scripts/i3-window-killer/install
@@ -13,15 +13,19 @@ PROGRAM_DIR="../../.bin/${PROGRAM_NAME}"
 BIN="target/release/${PROGRAM_NAME}"
 BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "${BASEDIR}" || die "cd ${BASEDIR}"
-[[ -d "${PROGRAM_DIR}" ]] || "cannot find submodule at \"${PROGRAM_DIR}\""
+
+[[ -d "${PROGRAM_DIR}" ]] || die "cannot find submodule at \"${PROGRAM_DIR}\""
 git submodule update --init "${PROGRAM_DIR}"
+
 read -p "[?] Update submodule ${PROGRAM_NAME} ? [y/N]: " UPDATE
 UPDATE="${UPDATE:-'N'}"
+log "> ${UPDATE}"
 [[ "${UPDATE}" == 'y' ]] && git submodule update --remote "${PROGRAM_DIR}"
+
 if [[ ! -e "${PROGRAM_DIR}/${BIN}" ]] || [[ "${UPDATE}" == 'y' ]]; then
   log "${PROGRAM_NAME} needs to be built"
   command -v cargo 2>&1 > /dev/null || die "cargo not installed"
-  local START="$(pwd)"
+  START="$(pwd)"
   cd "${PROGRAM_DIR}" || die "cd ${PROGRAM_DIR}"
   cargo b --release
   cd "${START}" || die "cd ${START}"
diff --git a/scripts/trizen/install b/scripts/trizen/install
--- a/scripts/trizen/install
+++ b/scripts/trizen/install
@@ -8,23 +8,20 @@ log() {
   echo "[#] ${1}."
 }
 
-if ! command -v trizen 2>&1 > /dev/null; then
-  read -p "[?] Install trizen ? [y/N]: " INSTALL
-  INSTALL="${INSTALL:-'N'}"
-  [[ "${INSTALL}" != 'y' ]] && log "Skipping trizen installation" && exit 0
-  log "Bootstraping trizen"
-  {
-    local CLONE_DIR="${HOME}/cloned/trizen"
-    mkdir -p "${CLONE_DIR}" || die "couldn't create cloning directory"
-    log "Installing trizen..."
-    git clone https://aur.archlinux.org/trizen.git "${CLONE_DIR}" || die "couldn't clone trizen"
-    local START="$(pwd)"
-    cd "${CLONE_DIR}" || die "cd ${CLONE_DIR}"
-    makepkg -sri
-    cd "${START}" || die "cd ${START}"
-    command -v trizen 2>&1 > /dev/null || die "trizen installation failed"
-    log "trizen successfully installed"
-  }
-else
-  log "trizen already installed"
-fi
+command -v trizen 2>&1 > /dev/null && log "trizen already installed" && exit 0
+read -p "[?] Install trizen ? [y/N]: " INSTALL
+INSTALL="${INSTALL:-'N'}"
+log "> ${INSTALL}"
+[[ "${INSTALL}" != 'y' ]] && log "Skipping trizen installation" && exit 0
+
+log "Bootstraping trizen"
+CLONE_DIR="${HOME}/.bin/trizen"
+mkdir -p "${CLONE_DIR}" || die "couldn't create cloning directory"
+log "Installing trizen..."
+git clone https://aur.archlinux.org/trizen.git "${CLONE_DIR}" || die "couldn't clone trizen"
+START="$(pwd)"
+cd "${CLONE_DIR}" || die "cd ${CLONE_DIR}"
+makepkg -sri
+cd "${START}" || die "cd ${START}"
+command -v trizen 2>&1 > /dev/null || die "trizen installation failed"
+log "trizen successfully installed"
