enhance!

diff --git a/scripts/packages/install b/scripts/packages/install
--- a/scripts/packages/install
+++ b/scripts/packages/install
@@ -1,20 +1,23 @@
 #!/usr/bin/env bash
-PACKAGES_FILE="package.list"
+PACKAGE_LIST="package.list"
 
 die() {
   echo "[-] Error: ${1}." >&2
   exit 1
 }
 log() {
-  echo "[+] ${1}."
+  echo "[#] ${1}."
 }
 
 BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "${BASEDIR}" || die "cd ${BASEDIR}"
+[[ -f "${PACKAGE_LIST}" ]] || die "couldn't find package list \"${PACKAGE_LIST}\""
+INSTALLED_LIST="$(trizen -Qq)"
+DIFF="$(comm -13 <(sort  <<<${INSTALLED_LIST}) <(sort ${PACKAGE_LIST}))"
+[[ -z "${DIFF}" ]] && log "All packages are already installed" && exit 0
+log "$(wc -l <<<"${DIFF}" | awk '{print $1}') packages need to be installed"
 read -p "[?] Install packages ? [y/N]: " INSTALL
 INSTALL="${INSTALL:-'N'}"
 [[ "${INSTALL}" != 'y' ]] && log "Skipping packages installation" && exit 0
-[[ -f "${PACKAGES_FILE}" ]] || die "couldn't find package list \"${PACKAGES_FILE}\""
-log "Package list contains $(wc -l $PACKAGES_FILE | awk '{print $1}') packages"
-trizen -Syu "${PACKAGES_FILE}"
+trizen -Sy - <<<"${DIFF}"
 log "Done installing packages"
